### ISSUE TITLE
How about participating in my TypeScript-STL?

### ISSUE THREAD

**Issue by samchon** [vovazolotoy/TypeScript-STL#1]
I'm also making a template container library named **TypeScript-STL**
- https://github.com/samchon/stl
- http://samchon.github.io/stl/api

Although my _TypeScript-STL_ is based on [C++ STL](http://www.cplusplus.com/reference/), so namings and grammers are differ from yours, the essential purpose is same. My _TypeScript-STL_, migration from C++ to TypeScript is almost done, however, internal logic and performance are not such good. Even I don't have enough conception about hash and heap what you've built.

Can you participate and help me to completing the **TypeScript-STL**?

**Comment by vovazolotoy** [comment]
Hi Jeongho,
Unfortunately, I will not have enough free time for help you with your library.

Thanks,
Vlad
